apiVersion: apps/v1
kind: Deployment # Set up the deployement kind
metadata:
  name: portfolio-deployment # Name for the deployement
  labels:
    app: portfolio
spec:
  replicas: 1 # Number of clones that we want
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: azurecloudstreakdemo.azurecr.io/portfolio-app:v1 # Container name that we pushed to ACR
          ports:
            - containerPort: 8045 # Container port number
--- # We can seperate file in YAML using --- dashes instead of writing them on seperate files
apiVersion: v1
kind: Service # Set up the service kind
metadata:
  name: portfolio-loadbalancer-service
  labels:
    app: portfolio
spec:
  type: LoadBalancer # Here we use load balancer service.
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 8045